const admin = require('firebase-admin');

// Path to your service account key JSON file
const serviceAccount = require('../sid-debattle-firebase-adminsdk-fbsvc-b12bed7830.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();
const TOPICS_COLLECTION = 'topics';

// Sample topics data
const topics = [
  {
    id: 'topic8',
    title: 'Should artificial intelligence replace human teachers in classrooms?',
    description: 'Debate whether AI can provide better personalized education than human instructors.',
    category: 'education',
    difficulty: 6,
    averageRating: 4.1,
    tags: ['AI', 'education', 'teaching', 'personalization'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T09:00:00Z')),
    usageCount: 0
  },
  {
    id: 'topic9',
    title: 'Is nuclear energy the best solution for clean power generation?',
    description: 'Examine nuclear power versus renewable energy sources for sustainable electricity.',
    category: 'science',
    difficulty: 7,
    averageRating: 4.2,
    tags: ['nuclear', 'renewable energy', 'environment', 'sustainability'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T10:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic10',
    title: 'Should companies be required to offer 4-day work weeks?',
    description: 'Debate the productivity and well-being impacts of shorter work weeks.',
    category: 'business',
    difficulty: 5,
    averageRating: 3.9,
    tags: ['work-life balance', 'productivity', 'employee welfare', 'business policy'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T11:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic11',
    title: 'Is genetic engineering of crops necessary to feed the world?',
    description: 'Discuss GMO crops versus organic farming for global food security.',
    category: 'science',
    difficulty: 8,
    averageRating: 4.4,
    tags: ['genetics', 'agriculture', 'food security', 'biotechnology'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T13:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic12',
    title: 'Should online learning completely replace traditional universities?',
    description: 'Compare the effectiveness of digital education versus campus-based learning.',
    category: 'education',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['online learning', 'higher education', 'digital transformation', 'accessibility'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T14:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic13',
    title: 'Is cryptocurrency a viable alternative to traditional banking?',
    description: 'Debate the future of digital currencies versus established financial systems.',
    category: 'technology',
    difficulty: 7,
    averageRating: 4.0,
    tags: ['cryptocurrency', 'blockchain', 'finance', 'decentralization'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T15:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic14',
    title: 'Should genetic therapy be used to enhance human capabilities?',
    description: 'Explore the ethics of using gene editing to improve human traits beyond medical needs.',
    category: 'science',
    difficulty: 9,
    averageRating: 4.5,
    tags: ['genetics', 'bioethics', 'human enhancement', 'CRISPR'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T16:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic15',
    title: 'Is remote work more productive than office-based work?',
    description: 'Compare productivity, collaboration, and innovation in remote versus traditional workspaces.',
    category: 'business',
    difficulty: 5,
    averageRating: 3.7,
    tags: ['remote work', 'productivity', 'collaboration', 'workplace culture'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T17:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic16',
    title: 'Should standardized testing be eliminated from education systems?',
    description: 'Debate whether standardized tests help or hinder student learning and assessment.',
    category: 'education',
    difficulty: 6,
    averageRating: 3.9,
    tags: ['testing', 'assessment', 'education reform', 'student evaluation'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T18:10:00Z')),
    usageCount: 0
  },
  {
    id: 'topic17',
    title: 'Is space exploration worth the enormous costs involved?',
    description: 'Examine whether space programs provide sufficient benefits to justify their expense.',
    category: 'science',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['space exploration', 'cost-benefit', 'scientific research', 'technology development'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T19:25:00Z')),
    usageCount: 0
  },
  {
    id: 'topic18',
    title: 'Should social media usage be regulated like tobacco and alcohol?',
    description: 'Debate whether social media addiction requires government intervention and regulation.',
    category: 'society',
    difficulty: 6,
    averageRating: 4.0,
    tags: ['social media', 'addiction', 'regulation', 'public health'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T20:00:00Z')),
    usageCount: 0
  },
  {
    id: 'topic19',
    title: 'Is lab-grown meat the future of sustainable food production?',
    description: 'Compare cultured meat with traditional livestock farming for environmental impact.',
    category: 'science',
    difficulty: 7,
    averageRating: 4.2,
    tags: ['lab-grown meat', 'sustainability', 'agriculture', 'food technology'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T21:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic20',
    title: 'Should coding be a mandatory subject in all schools?',
    description: 'Debate whether programming skills are essential for all students in the digital age.',
    category: 'education',
    difficulty: 5,
    averageRating: 3.8,
    tags: ['coding', 'programming', 'digital literacy', 'curriculum'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-16T22:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic21',
    title: 'Is the gig economy beneficial or harmful to workers?',
    description: 'Examine the pros and cons of freelance work versus traditional employment.',
    category: 'business',
    difficulty: 6,
    averageRating: 3.9,
    tags: ['gig economy', 'freelancing', 'worker rights', 'job security'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T08:00:00Z')),
    usageCount: 0
  },
  {
    id: 'topic22',
    title: 'Should virtual reality replace traditional textbooks in classrooms?',
    description: 'Compare immersive VR learning experiences with conventional educational materials.',
    category: 'technology',
    difficulty: 6,
    averageRating: 4.0,
    tags: ['virtual reality', 'education technology', 'immersive learning', 'textbooks'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T09:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic23',
    title: 'Is climate engineering a necessary solution to global warming?',
    description: 'Debate geoengineering techniques versus emission reduction for climate change.',
    category: 'science',
    difficulty: 8,
    averageRating: 4.3,
    tags: ['geoengineering', 'climate change', 'environmental science', 'technology'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T10:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic24',
    title: 'Should museums return all artifacts to their countries of origin?',
    description: 'Examine cultural repatriation versus global accessibility of historical artifacts.',
    category: 'society',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['cultural heritage', 'museums', 'repatriation', 'history'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T11:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic25',
    title: 'Is artificial intelligence creative or just mimicking human creativity?',
    description: 'Debate whether AI can truly create original art, music, and literature.',
    category: 'technology',
    difficulty: 8,
    averageRating: 4.4,
    tags: ['AI creativity', 'artificial intelligence', 'art', 'originality'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T12:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic26',
    title: 'Should homework be banned in elementary schools?',
    description: 'Examine the educational value versus stress impact of homework for young children.',
    category: 'education',
    difficulty: 5,
    averageRating: 3.7,
    tags: ['homework', 'elementary education', 'child development', 'stress'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T13:35:00Z')),
    usageCount: 0
  },
  {
    id: 'topic27',
    title: 'Is sustainable fashion possible in fast fashion industry?',
    description: 'Debate whether the fashion industry can become environmentally sustainable while remaining profitable.',
    category: 'business',
    difficulty: 6,
    averageRating: 3.9,
    tags: ['sustainable fashion', 'fast fashion', 'environment', 'consumer behavior'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T14:50:00Z')),
    usageCount: 0
  },
  {
    id: 'topic28',
    title: 'Should human cloning be allowed for medical purposes?',
    description: 'Explore therapeutic cloning benefits versus ethical concerns about human reproduction.',
    category: 'science',
    difficulty: 9,
    averageRating: 4.5,
    tags: ['cloning', 'bioethics', 'medical research', 'stem cells'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T15:25:00Z')),
    usageCount: 0
  },
  {
    id: 'topic29',
    title: 'Is urban vertical farming the solution to food security?',
    description: 'Compare vertical farming with traditional agriculture for feeding growing populations.',
    category: 'technology',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['vertical farming', 'urban agriculture', 'food security', 'sustainability'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T16:40:00Z')),
    usageCount: 0
  },
  {
    id: 'topic30',
    title: 'Should plastic packaging be completely eliminated?',
    description: 'Debate plastic alternatives versus the practical benefits of plastic packaging.',
    category: 'society',
    difficulty: 6,
    averageRating: 4.0,
    tags: ['plastic pollution', 'packaging', 'environment', 'alternatives'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T17:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic31',
    title: 'Is quantum computing a threat to current cybersecurity?',
    description: 'Examine quantum computing impact on encryption and digital security systems.',
    category: 'technology',
    difficulty: 8,
    averageRating: 4.3,
    tags: ['quantum computing', 'cybersecurity', 'encryption', 'technology'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T18:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic32',
    title: 'Should students be allowed to use AI tools for academic work?',
    description: 'Debate AI assistance in education versus traditional learning and assessment methods.',
    category: 'education',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['AI in education', 'academic integrity', 'learning tools', 'assessment'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T19:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic33',
    title: 'Is biodegradable plastic the ultimate solution to pollution?',
    description: 'Compare biodegradable plastics with other sustainable material alternatives.',
    category: 'science',
    difficulty: 7,
    averageRating: 4.0,
    tags: ['biodegradable plastic', 'pollution', 'materials science', 'sustainability'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T20:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic34',
    title: 'Should companies prioritize profit or social responsibility?',
    description: 'Examine corporate social responsibility versus shareholder profit maximization.',
    category: 'business',
    difficulty: 6,
    averageRating: 3.9,
    tags: ['corporate responsibility', 'profit', 'ethics', 'stakeholder capitalism'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T21:35:00Z')),
    usageCount: 0
  },
  {
    id: 'topic35',
    title: 'Is fusion energy the holy grail of clean power?',
    description: 'Debate fusion energy potential versus current renewable energy investments.',
    category: 'science',
    difficulty: 8,
    averageRating: 4.4,
    tags: ['fusion energy', 'clean power', 'renewable energy', 'nuclear physics'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-17T22:10:00Z')),
    usageCount: 0
  },
  {
    id: 'topic36',
    title: 'Should social media platforms ban anonymous accounts?',
    description: 'Debate online anonymity versus accountability and harassment prevention.',
    category: 'society',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['anonymity', 'social media', 'privacy', 'accountability'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T08:25:00Z')),
    usageCount: 0
  },
  {
    id: 'topic37',
    title: 'Is brain-computer interface technology ready for widespread adoption?',
    description: 'Examine the benefits and risks of direct neural interface technology.',
    category: 'technology',
    difficulty: 8,
    averageRating: 4.2,
    tags: ['brain-computer interface', 'neurotechnology', 'medical devices', 'ethics'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T09:40:00Z')),
    usageCount: 0
  },
  {
    id: 'topic38',
    title: 'Should financial literacy be mandatory in high school curriculum?',
    description: 'Debate the importance of teaching money management and investment basics to teenagers.',
    category: 'education',
    difficulty: 5,
    averageRating: 3.9,
    tags: ['financial literacy', 'curriculum', 'money management', 'life skills'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T10:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic39',
    title: 'Is 3D printing revolutionizing manufacturing or just a novelty?',
    description: 'Compare additive manufacturing benefits with traditional production methods.',
    category: 'technology',
    difficulty: 6,
    averageRating: 4.0,
    tags: ['3D printing', 'manufacturing', 'additive manufacturing', 'production'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T11:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic40',
    title: 'Should animal testing be completely banned for cosmetics research?',
    description: 'Examine alternatives to animal testing versus product safety requirements.',
    category: 'science',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['animal testing', 'cosmetics', 'research ethics', 'alternatives'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T12:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic41',
    title: 'Is subscription-based software better than one-time purchases?',
    description: 'Compare software as a service models with traditional software ownership.',
    category: 'business',
    difficulty: 5,
    averageRating: 3.7,
    tags: ['software licensing', 'subscription model', 'SaaS', 'consumer choice'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T13:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic42',
    title: 'Should cities ban private car ownership in favor of public transport?',
    description: 'Debate urban mobility solutions and environmental impact of personal vehicles.',
    category: 'society',
    difficulty: 7,
    averageRating: 4.0,
    tags: ['urban planning', 'public transport', 'environment', 'mobility'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T14:35:00Z')),
    usageCount: 0
  },
  {
    id: 'topic43',
    title: 'Is artificial photosynthesis the key to carbon capture?',
    description: 'Examine artificial photosynthesis technology for atmospheric CO2 reduction.',
    category: 'science',
    difficulty: 8,
    averageRating: 4.3,
    tags: ['artificial photosynthesis', 'carbon capture', 'climate technology', 'biochemistry'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T15:50:00Z')),
    usageCount: 0
  },
  {
    id: 'topic44',
    title: 'Should children start learning second languages before age 5?',
    description: 'Debate early childhood language acquisition versus cognitive development priorities.',
    category: 'education',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['language learning', 'early childhood', 'cognitive development', 'multilingualism'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T16:25:00Z')),
    usageCount: 0
  },
  {
    id: 'topic45',
    title: 'Is blockchain technology overhyped or underutilized?',
    description: 'Examine practical applications of blockchain beyond cryptocurrency.',
    category: 'technology',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['blockchain', 'distributed ledger', 'technology adoption', 'applications'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T17:40:00Z')),
    usageCount: 0
  },
  {
    id: 'topic46',
    title: 'Should performance-enhancing drugs be allowed in competitive sports?',
    description: 'Debate fairness, safety, and human enhancement in athletic competition.',
    category: 'society',
    difficulty: 7,
    averageRating: 3.9,
    tags: ['sports', 'performance enhancement', 'fairness', 'competition'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T18:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic47',
    title: 'Is telecommuting killing workplace innovation and collaboration?',
    description: 'Examine remote work impact on creativity, teamwork, and company culture.',
    category: 'business',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['telecommuting', 'innovation', 'collaboration', 'workplace culture'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T19:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic48',
    title: 'Should we terraform Mars or fix Earth first?',
    description: 'Debate planetary colonization versus addressing Earth\'s environmental challenges.',
    category: 'science',
    difficulty: 8,
    averageRating: 4.2,
    tags: ['terraforming', 'Mars colonization', 'environmental restoration', 'space exploration'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T20:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic49',
    title: 'Is gamification effective in education and workplace training?',
    description: 'Examine game elements in learning and professional development effectiveness.',
    category: 'education',
    difficulty: 6,
    averageRating: 3.9,
    tags: ['gamification', 'learning', 'training', 'engagement'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T21:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic50',
    title: 'Should autonomous vehicles prioritize passenger or pedestrian safety?',
    description: 'Debate ethical programming decisions in self-driving car safety systems.',
    category: 'technology',
    difficulty: 8,
    averageRating: 4.4,
    tags: ['autonomous vehicles', 'ethics', 'safety', 'moral dilemma'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-18T22:35:00Z')),
    usageCount: 0
  },
  {
    id: 'topic51',
    title: 'Is mental health screening mandatory in schools beneficial or invasive?',
    description: 'Debate early mental health intervention versus privacy concerns for students.',
    category: 'society',
    difficulty: 7,
    averageRating: 4.0,
    tags: ['mental health', 'school screening', 'privacy', 'student welfare'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T08:10:00Z')),
    usageCount: 0
  },
  {
    id: 'topic52',
    title: 'Should companies adopt unlimited vacation policies?',
    description: 'Examine unlimited PTO benefits versus potential abuse and productivity concerns.',
    category: 'business',
    difficulty: 5,
    averageRating: 3.7,
    tags: ['vacation policy', 'employee benefits', 'work-life balance', 'productivity'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T09:25:00Z')),
    usageCount: 0
  },
  {
    id: 'topic53',
    title: 'Is gene drive technology safe for mosquito population control?',
    description: 'Debate genetically modified mosquitoes for disease prevention versus ecological risks.',
    category: 'science',
    difficulty: 9,
    averageRating: 4.5,
    tags: ['gene drive', 'mosquito control', 'genetic engineering', 'public health'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T10:40:00Z')),
    usageCount: 0
  },
  {
    id: 'topic54',
    title: 'Should schools replace traditional grades with competency-based assessment?',
    description: 'Compare skill-based evaluation with conventional letter grade systems.',
    category: 'education',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['competency-based learning', 'assessment', 'grading systems', 'education reform'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T11:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic55',
    title: 'Is augmented reality the future of retail shopping?',
    description: 'Examine AR technology impact on consumer experience and traditional retail.',
    category: 'technology',
    difficulty: 6,
    averageRating: 4.0,
    tags: ['augmented reality', 'retail', 'shopping experience', 'e-commerce'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T12:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic56',
    title: 'Should plastic surgery be covered by universal healthcare?',
    description: 'Debate cosmetic procedures versus medical necessity in public health coverage.',
    category: 'society',
    difficulty: 7,
    averageRating: 3.9,
    tags: ['healthcare', 'plastic surgery', 'medical coverage', 'public health'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T13:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic57',
    title: 'Is peer-to-peer lending safer than traditional banking?',
    description: 'Compare P2P lending platforms with conventional bank loan systems.',
    category: 'business',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['peer-to-peer lending', 'financial services', 'banking', 'risk assessment'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T14:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic58',
    title: 'Should artificial meat production replace livestock farming?',
    description: 'Debate lab-grown meat benefits versus traditional agriculture and cultural practices.',
    category: 'science',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['artificial meat', 'livestock', 'sustainability', 'food production'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T15:35:00Z')),
    usageCount: 0
  },
  {
    id: 'topic59',
    title: 'Is microlearning more effective than traditional lengthy courses?',
    description: 'Compare bite-sized learning modules with comprehensive educational programs.',
    category: 'education',
    difficulty: 5,
    averageRating: 3.8,
    tags: ['microlearning', 'education format', 'learning efficiency', 'attention span'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T16:10:00Z')),
    usageCount: 0
  },
  {
    id: 'topic60',
    title: 'Should social credit systems be implemented globally?',
    description: 'Debate behavioral scoring systems for social accountability versus privacy rights.',
    category: 'society',
    difficulty: 8,
    averageRating: 4.2,
    tags: ['social credit', 'behavioral scoring', 'privacy', 'social control'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T17:25:00Z')),
    usageCount: 0
  },
  {
    id: 'topic61',
    title: 'Is cloud computing more secure than on-premise data storage?',
    description: 'Compare cloud security benefits with local data control and privacy.',
    category: 'technology',
    difficulty: 7,
    averageRating: 4.0,
    tags: ['cloud computing', 'data security', 'privacy', 'infrastructure'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T18:40:00Z')),
    usageCount: 0
  },
  {
    id: 'topic62',
    title: 'Should employee productivity be monitored using AI surveillance?',
    description: 'Debate workplace AI monitoring versus employee privacy and trust.',
    category: 'business',
    difficulty: 7,
    averageRating: 3.9,
    tags: ['workplace surveillance', 'AI monitoring', 'privacy', 'productivity'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T19:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic63',
    title: 'Is desalination technology the solution to global water scarcity?',
    description: 'Examine seawater desalination benefits versus environmental and energy costs.',
    category: 'science',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['desalination', 'water scarcity', 'environmental impact', 'technology'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T20:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic64',
    title: 'Should children have access to smartphones before age 12?',
    description: 'Debate early smartphone access benefits versus developmental and social concerns.',
    category: 'society',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['smartphones', 'children', 'technology access', 'development'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T21:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic65',
    title: 'Is personalized medicine worth the privacy trade-offs?',
    description: 'Compare genetic data benefits for healthcare with privacy and discrimination risks.',
    category: 'science',
    difficulty: 8,
    averageRating: 4.3,
    tags: ['personalized medicine', 'genetic data', 'privacy', 'healthcare'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-19T22:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic66',
    title: 'Should schools eliminate letter grades entirely?',
    description: 'Debate alternative assessment methods versus traditional grading systems.',
    category: 'education',
    difficulty: 6,
    averageRating: 3.7,
    tags: ['grading systems', 'assessment', 'education reform', 'student evaluation'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T08:35:00Z')),
    usageCount: 0
  },
  {
    id: 'topic67',
    title: 'Is voice-activated technology making us lazier or more efficient?',
    description: 'Examine smart speakers and voice assistants impact on daily productivity and skills.',
    category: 'technology',
    difficulty: 5,
    averageRating: 3.9,
    tags: ['voice technology', 'smart assistants', 'productivity', 'dependency'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T09:10:00Z')),
    usageCount: 0
  },
  {
    id: 'topic68',
    title: 'Should companies be required to disclose their environmental impact?',
    description: 'Debate mandatory environmental reporting versus business autonomy and costs.',
    category: 'business',
    difficulty: 6,
    averageRating: 4.0,
    tags: ['environmental disclosure', 'corporate transparency', 'sustainability', 'regulation'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T10:25:00Z')),
    usageCount: 0
  },
  {
    id: 'topic69',
    title: 'Is renewable energy storage technology ready to replace fossil fuels?',
    description: 'Examine battery and storage solutions for complete renewable energy transition.',
    category: 'science',
    difficulty: 8,
    averageRating: 4.2,
    tags: ['energy storage', 'renewable energy', 'battery technology', 'grid stability'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T11:40:00Z')),
    usageCount: 0
  },
  {
    id: 'topic70',
    title: 'Should urban areas implement congestion pricing for traffic?',
    description: 'Debate road pricing benefits versus accessibility and social equity concerns.',
    category: 'society',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['congestion pricing', 'urban planning', 'traffic management', 'equity'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T12:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic71',
    title: 'Is artificial intelligence biased or are humans projecting their biases?',
    description: 'Examine AI bias origins and responsibility for discriminatory algorithmic decisions.',
    category: 'technology',
    difficulty: 8,
    averageRating: 4.4,
    tags: ['AI bias', 'algorithmic fairness', 'discrimination', 'machine learning'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T13:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic72',
    title: 'Should universities offer degrees entirely through virtual reality?',
    description: 'Compare immersive VR education with traditional campus-based learning experiences.',
    category: 'education',
    difficulty: 7,
    averageRating: 3.9,
    tags: ['VR education', 'virtual university', 'immersive learning', 'higher education'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T14:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic73',
    title: 'Is corporate whistleblowing a moral duty or betrayal of loyalty?',
    description: 'Debate employee responsibility to expose wrongdoing versus organizational loyalty.',
    category: 'business',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['whistleblowing', 'corporate ethics', 'loyalty', 'moral responsibility'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T15:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic74',
    title: 'Should genetic modification be used to eliminate hereditary diseases?',
    description: 'Debate gene editing for disease prevention versus natural genetic diversity.',
    category: 'science',
    difficulty: 9,
    averageRating: 4.5,
    tags: ['genetic modification', 'hereditary diseases', 'gene editing', 'medical ethics'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T16:35:00Z')),
    usageCount: 0
  },
  {
    id: 'topic75',
    title: 'Is digital minimalism beneficial in our hyperconnected world?',
    description: 'Examine reduced technology use benefits versus professional and social connectivity needs.',
    category: 'society',
    difficulty: 6,
    averageRating: 3.9,
    tags: ['digital minimalism', 'technology detox', 'connectivity', 'mental health'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T17:10:00Z')),
    usageCount: 0
  },
  {
    id: 'topic76',
    title: 'Should machine learning algorithms decide loan approvals?',
    description: 'Debate AI lending decisions versus human judgment for fairness and accuracy.',
    category: 'technology',
    difficulty: 7,
    averageRating: 4.0,
    tags: ['machine learning', 'loan approval', 'financial decisions', 'algorithmic bias'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T18:25:00Z')),
    usageCount: 0
  },
  {
    id: 'topic77',
    title: 'Is project-based learning superior to traditional classroom instruction?',
    description: 'Compare hands-on project learning with conventional lecture-based education.',
    category: 'education',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['project-based learning', 'hands-on education', 'classroom instruction', 'pedagogy'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T19:40:00Z')),
    usageCount: 0
  },
  {
    id: 'topic78',
    title: 'Should businesses adopt stakeholder capitalism over shareholder primacy?',
    description: 'Debate multi-stakeholder business models versus traditional profit maximization.',
    category: 'business',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['stakeholder capitalism', 'shareholder primacy', 'business ethics', 'corporate governance'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T20:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic79',
    title: 'Is synthetic biology the key to solving climate change?',
    description: 'Examine engineered organisms for carbon capture versus natural climate solutions.',
    category: 'science',
    difficulty: 8,
    averageRating: 4.3,
    tags: ['synthetic biology', 'climate change', 'engineered organisms', 'biotechnology'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T21:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic80',
    title: 'Should digital art be valued equally to traditional physical art?',
    description: 'Debate NFTs and digital artwork value versus traditional art market preferences.',
    category: 'society',
    difficulty: 6,
    averageRating: 3.7,
    tags: ['digital art', 'NFTs', 'art valuation', 'cultural value'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-20T22:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic81',
    title: 'Is edge computing more important than cloud computing for future technology?',
    description: 'Compare distributed edge processing with centralized cloud infrastructure.',
    category: 'technology',
    difficulty: 7,
    averageRating: 4.0,
    tags: ['edge computing', 'cloud computing', 'distributed systems', 'latency'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T08:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic82',
    title: 'Should emotional intelligence be taught as a core subject in schools?',
    description: 'Debate emotional skills education versus traditional academic subject priorities.',
    category: 'education',
    difficulty: 5,
    averageRating: 3.9,
    tags: ['emotional intelligence', 'social skills', 'curriculum', 'child development'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T09:35:00Z')),
    usageCount: 0
  },
  {
    id: 'topic83',
    title: 'Is sustainable investing more profitable than traditional investment strategies?',
    description: 'Compare ESG investing returns with conventional profit-focused investment approaches.',
    category: 'business',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['sustainable investing', 'ESG', 'investment returns', 'financial performance'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T10:10:00Z')),
    usageCount: 0
  },
  {
    id: 'topic84',
    title: 'Should marine protected areas be expanded globally?',
    description: 'Debate ocean conservation benefits versus fishing industry and economic impacts.',
    category: 'science',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['marine conservation', 'protected areas', 'ocean ecosystems', 'fishing industry'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T11:25:00Z')),
    usageCount: 0
  },
  {
    id: 'topic85',
    title: 'Is universal internet access a basic human right?',
    description: 'Debate internet connectivity as fundamental right versus infrastructure and cost challenges.',
    category: 'society',
    difficulty: 6,
    averageRating: 4.0,
    tags: ['internet access', 'human rights', 'digital divide', 'connectivity'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T12:40:00Z')),
    usageCount: 0
  },
  {
    id: 'topic86',
    title: 'Should robotic automation replace human workers in dangerous jobs?',
    description: 'Examine robot safety benefits versus job displacement and human skill value.',
    category: 'technology',
    difficulty: 6,
    averageRating: 3.9,
    tags: ['robotic automation', 'workplace safety', 'job displacement', 'dangerous jobs'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T13:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic87',
    title: 'Is lifelong learning essential for career success in the modern economy?',
    description: 'Debate continuous education necessity versus specialized expertise development.',
    category: 'education',
    difficulty: 5,
    averageRating: 3.8,
    tags: ['lifelong learning', 'career development', 'skill acquisition', 'professional growth'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T14:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic88',
    title: 'Should companies adopt circular economy principles?',
    description: 'Compare waste reduction and reuse business models with traditional linear production.',
    category: 'business',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['circular economy', 'waste reduction', 'sustainability', 'business models'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T15:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic89',
    title: 'Is carbon dioxide removal technology necessary for climate goals?',
    description: 'Debate direct air capture and carbon removal versus emission reduction priorities.',
    category: 'science',
    difficulty: 8,
    averageRating: 4.2,
    tags: ['carbon removal', 'direct air capture', 'climate technology', 'emissions'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T16:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic90',
    title: 'Should social media algorithms be transparent to users?',
    description: 'Debate algorithmic transparency benefits versus platform competitive advantages.',
    category: 'society',
    difficulty: 6,
    averageRating: 3.9,
    tags: ['algorithmic transparency', 'social media', 'user awareness', 'platform regulation'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T17:35:00Z')),
    usageCount: 0
  },
  {
    id: 'topic91',
    title: 'Is 5G technology worth the infrastructure investment and health concerns?',
    description: 'Examine 5G benefits versus deployment costs and potential health risks.',
    category: 'technology',
    difficulty: 7,
    averageRating: 4.0,
    tags: ['5G technology', 'infrastructure', 'health concerns', 'connectivity'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T18:10:00Z')),
    usageCount: 0
  },
  {
    id: 'topic92',
    title: 'Should creativity and arts education be prioritized equally with STEM?',
    description: 'Debate balanced education approach versus STEM focus for economic competitiveness.',
    category: 'education',
    difficulty: 6,
    averageRating: 3.8,
    tags: ['arts education', 'STEM', 'creativity', 'curriculum balance'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T19:25:00Z')),
    usageCount: 0
  },
  {
    id: 'topic93',
    title: 'Is corporate social responsibility genuine or just marketing?',
    description: 'Examine authentic corporate responsibility versus public relations and greenwashing.',
    category: 'business',
    difficulty: 6,
    averageRating: 3.7,
    tags: ['corporate responsibility', 'greenwashing', 'marketing', 'authentic values'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T20:40:00Z')),
    usageCount: 0
  },
  {
    id: 'topic94',
    title: 'Should artificial coral reefs replace damaged natural reefs?',
    description: 'Debate artificial reef technology versus natural coral restoration efforts.',
    category: 'science',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['artificial reefs', 'coral restoration', 'marine ecosystems', 'ocean conservation'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T21:15:00Z')),
    usageCount: 0
  },
  {
    id: 'topic95',
    title: 'Is digital privacy dead in the age of big data?',
    description: 'Examine data collection realities versus individual privacy rights and expectations.',
    category: 'society',
    difficulty: 7,
    averageRating: 4.0,
    tags: ['digital privacy', 'big data', 'data collection', 'privacy rights'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T22:30:00Z')),
    usageCount: 0
  },
  {
    id: 'topic96',
    title: 'Should predictive policing algorithms be used in law enforcement?',
    description: 'Debate crime prediction technology benefits versus bias and civil liberties concerns.',
    category: 'technology',
    difficulty: 8,
    averageRating: 4.2,
    tags: ['predictive policing', 'algorithmic bias', 'law enforcement', 'civil liberties'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-21T23:45:00Z')),
    usageCount: 0
  },
  {
    id: 'topic97',
    title: 'Is peer review the best system for validating scientific research?',
    description: 'Examine traditional peer review versus alternative research validation methods.',
    category: 'science',
    difficulty: 7,
    averageRating: 4.1,
    tags: ['peer review', 'scientific validation', 'research quality', 'academic publishing'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-22T08:20:00Z')),
    usageCount: 0
  },
  {
    id: 'topic98',
    title: 'Should skill-based hiring replace degree requirements?',
    description: 'Debate competency-based employment versus traditional educational credentials.',
    category: 'business',
    difficulty: 6,
    averageRating: 3.9,
    tags: ['skill-based hiring', 'degree requirements', 'competency', 'employment'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-22T09:35:00Z')),
    usageCount: 0
  },
  {
    id: 'topic99',
    title: 'Is mindfulness meditation effective for improving academic performance?',
    description: 'Examine meditation benefits for student focus and learning versus time allocation concerns.',
    category: 'education',
    difficulty: 5,
    averageRating: 3.8,
    tags: ['mindfulness', 'meditation', 'academic performance', 'student wellness'],
    isOfficial: true,
    trending: false,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-22T10:10:00Z')),
    usageCount: 0
  },
  {
    id: 'topic100',
    title: 'Should human consciousness be digitally preserved after death?',
    description: 'Debate digital immortality technology versus natural life cycles and resource allocation.',
    category: 'technology',
    difficulty: 9,
    averageRating: 4.5,
    tags: ['digital consciousness', 'immortality', 'technology ethics', 'human identity'],
    isOfficial: true,
    trending: true,
    createdAt: admin.firestore.Timestamp.fromDate(new Date('2025-07-22T11:25:00Z')),
    usageCount: 0
  }
];

async function addTopics() {
  try {
    const batch = db.batch();
    const topicsRef = db.collection(TOPICS_COLLECTION);
    
    // Add each topic to the batch
    topics.forEach(topic => {
      const docRef = topicsRef.doc(topic.id);
      batch.set(docRef, topic);
    });
    
    // Commit the batch
    await batch.commit();
    
    console.log(`Successfully added ${topics.length} topics.`);
    process.exit(0);
  } catch (error) {
    console.error('Error adding topics:', error);
    process.exit(1);
  }
}

// Run the function
addTopics();
